# Generated by Django 5.1.1 on 2024-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posttime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dj_api',
            },
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNum', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255)),
                ('PhoneNum', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'user_basic_inf',
            },
        ),
        migrations.CreateModel(
            name='User_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNum', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'user_basic_photo',
            },
        ),
    ]
